USE master
GO

CREATE DATABASE AceleraPlenoDB
GO

USE AceleraPlenoDB
GO


CREATE TABLE dbo."00t_PARAMETRIZACAO" 
    (
     IDPARAMETRIZACAO INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     CODALTERADOPOR INTEGER NOT NULL , 
     DIRETORIO NVARCHAR (200) , 
     TEMPOPROCESSAMENTO INTEGER , 
     DATAHORAALTERACAO DATETIME2 
    )
GO

ALTER TABLE dbo."00t_PARAMETRIZACAO" ADD CONSTRAINT "00t_PARAMETRIZACAO_PK" PRIMARY KEY CLUSTERED (IDPARAMETRIZACAO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."01t_CARGA" 
    (
     IDCARGA INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDUSUARIOSISTEMA INTEGER NOT NULL , 
     DESCARQUIVO NVARCHAR (100) NOT NULL , 
     TIPOARQUIVO NVARCHAR (50) NOT NULL , 
     DIRETORIO NVARCHAR (200) NOT NULL , 
     ESTADOCARGA INTEGER NOT NULL , 
     MENSAGEMERRO NVARCHAR (200) , 
     DATAHORACARGA DATETIME2 NOT NULL 
    )
GO

ALTER TABLE dbo."01t_CARGA" ADD CONSTRAINT "01t_CARGA_PK" PRIMARY KEY CLUSTERED (IDCARGA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."02t_USUARIOSISTEMA" 
    (
     IDUSUARIOSISTEMA INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDUSUARIO NVARCHAR (100) NOT NULL , 
     LOGIN NVARCHAR (50) NOT NULL , 
     PASSWORD NVARCHAR (50) NOT NULL , 
     SECRETKEY NVARCHAR (100) NOT NULL , 
     BOLPRIMEIROLOGIN INTEGER NOT NULL , 
     ULTIMOLOGIN DATETIME2 , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."02t_USUARIOSISTEMA" ADD CONSTRAINT "02t_USUARIOSISTEMA_PK" PRIMARY KEY CLUSTERED (IDUSUARIOSISTEMA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."03t_GRUPOACESSO" 
    (
     IDGRUPOACESSO INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     DESCGRUPOACESSO NVARCHAR (50) , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."03t_GRUPOACESSO" ADD CONSTRAINT "00t_GRUPOACESSO_PK" PRIMARY KEY CLUSTERED (IDGRUPOACESSO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."04t_USUARIOSISTEMAGRUPOACESSO" 
    (
     IDUSUARIOSISTEMAGRUPOACESSO INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDUSUARIOSISTEMA INTEGER NOT NULL , 
     IDGRUPOACESSO INTEGER NOT NULL 
    )
GO

ALTER TABLE dbo."04t_USUARIOSISTEMAGRUPOACESSO" ADD CONSTRAINT "00t_USUARIOSISTEMAGRUPOACESSO_PK" PRIMARY KEY CLUSTERED (IDUSUARIOSISTEMAGRUPOACESSO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."05t_UNIDADEINSTITUICAO" 
    (
     IDUNIDADEINST NVARCHAR (10) NOT NULL , 
     IDINSTITUICAO INTEGER NOT NULL , 
     NUMCNPJ NVARCHAR (20) , 
     NOMEUNIDADE NVARCHAR (200) NOT NULL , 
     SIGLAUNIDADE NVARCHAR (50) NOT NULL , 
     DATACADASTRAMENTO DATETIME NOT NULL , 
     CODTIPOINSTITUICAO INTEGER NOT NULL , 
     CODTIPOUNIDADE INTEGER NOT NULL , 
     DATAINICIOSICOOB DATETIME , 
     DATAFIMSICOOB DATETIME , 
     NUMCHECKALTERACAO INTEGER NOT NULL , 
     IDUNIDADEINSTRESP INTEGER , 
     CODSITUACAOUNID INTEGER NOT NULL , 
     NUMSIRC INTEGER , 
     DESCENDINTERNET NVARCHAR (100) , 
     DATAINICIOUTILIZACAOMARCASICOOB DATETIME , 
     BOLATENDIMENTOPUBLICOEXTERNO INTEGER , 
     NUMINSCRICAOMUNICIPAL NVARCHAR (50) , 
     NUMNIRE NVARCHAR (50) , 
     IDINSTITUICAOINCORPORADORA INTEGER , 
     DATAINCORPORACAO DATETIME , 
     BOLUTILIZACOMPARTILHAMENTO INTEGER , 
     DATAINICIOFUNCIONAMENTO DATETIME , 
     DATAFIMFUNCIONAMENTO DATETIME , 
     BOLUTILIZASISBR INTEGER NOT NULL , 
     DATAINICIOUTILIZASISBR DATETIME , 
     DATAFIMUTILIZASISBR DATETIME , 
     BOLISENTOINSCRICAOMUNICIPAL INTEGER , 
     BOLISENTONIRE INTEGER , 
     BOLSINALIZADOSICOOB INTEGER , 
     BOLPAINCORPORADO INTEGER , 
     DATAHORACARGA DATETIME2 , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."05t_UNIDADEINSTITUICAO" ADD CONSTRAINT "06t_UNIDADEINSTITUICAO_PK" PRIMARY KEY CLUSTERED (IDUNIDADEINST)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."06t_TRANSPORTADORAVALORES" 
    (
     IDTRANSPORTADORAVALORES INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     NUMCNPJ NVARCHAR (50) NOT NULL , 
     DESCTRANSPORTADORA NVARCHAR (100) NOT NULL , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."06t_TRANSPORTADORAVALORES" ADD CONSTRAINT "03t_TRANSPORTADORAVALORES_PK" PRIMARY KEY CLUSTERED (IDTRANSPORTADORAVALORES)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."07t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES" 
    (
     IDUNIDADEINSTTRANSPORTADORAVALORES INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDTRANSPORTADORAVALORES INTEGER NOT NULL , 
     IDUNIDADEINST NVARCHAR (10) NOT NULL 
    )
GO

ALTER TABLE dbo."07t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES" ADD CONSTRAINT "00t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES_PK" PRIMARY KEY CLUSTERED (IDUNIDADEINSTTRANSPORTADORAVALORES)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."08t_TIPOTERMINAL" 
    (
     IDTIPOTERMINAL INTEGER NOT NULL , 
     IDUNIDADEINST NVARCHAR (10) NOT NULL , 
     DESCTIPOTERMINAL NVARCHAR (100) NOT NULL , 
     BOLACESSOLIBERADO INTEGER NOT NULL , 
     NUMCHEKALTERACAO INTEGER NOT NULL , 
     LIMSUPERIOR INTEGER NOT NULL , 
     LIMINFERIOR INTEGER NOT NULL , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."08t_TIPOTERMINAL" ADD CONSTRAINT "04t_TIPOTERMINAL_PK" PRIMARY KEY CLUSTERED (IDTIPOTERMINAL)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."09t_TIPOOPERACAO" 
    (
     IDTIPOOPERACAO INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDGRUPOCAIXA INTEGER NOT NULL , 
     IDOPERACAOCAIXA INTEGER NOT NULL , 
     OPERACAO NVARCHAR (10) NOT NULL , 
     DESCOPERACAO NVARCHAR (100) NOT NULL , 
     CODHISTORICO INTEGER NOT NULL , 
     DESCHISTORICO NVARCHAR (100) NOT NULL , 
     SENSIBILIZACAO NCHAR (1) NOT NULL , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."09t_TIPOOPERACAO" ADD CONSTRAINT "08t_TIPOOPERACAO_PK" PRIMARY KEY CLUSTERED (IDTIPOOPERACAO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."10t_OPERACAO" 
    (
     IDOPERACAO INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     IDTIPOOPERACAO INTEGER NOT NULL , 
     IDTIPOTERMINAL INTEGER NOT NULL , 
     IDUNIDADEINST NVARCHAR (10) NOT NULL , 
     OPERACAO NVARCHAR (10) NOT NULL , 
     DESCOPERACAO NVARCHAR (100) NOT NULL , 
     CODHISTORICO INTEGER NOT NULL , 
     DESCHISTORICO NVARCHAR (100) NOT NULL , 
     DATAOPERACAO DATETIME2 NOT NULL , 
     TERMINAL NVARCHAR (50) , 
     CODAUT NVARCHAR (10) , 
     VALOR MONEY NOT NULL , 
     SENSIBILIZACAO NCHAR (1) NOT NULL , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."10t_OPERACAO" ADD CONSTRAINT "05t_OPERACAO_PK" PRIMARY KEY CLUSTERED (IDOPERACAO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."11t_USUARIO" 
    (
     IDUSUARIO NVARCHAR (100) NOT NULL , 
     IDUNIDADEINST NVARCHAR (10) NOT NULL , 
     IDINSTITUICAO INTEGER NOT NULL , 
     NUMCHECKALTERACAO INTEGER NOT NULL , 
     IDINSTITUICAOUSUARIO INTEGER NOT NULL , 
     DESCNOMEUSUARIO NVARCHAR (200) , 
     BOLHABILITADOUSUARIO INTEGER NOT NULL , 
     DESCSTATUSUSUARIO NVARCHAR (50) , 
     BOLVERIFICANOMEMAQUINA INTEGER NOT NULL , 
     DESCEMAIL NVARCHAR (100) , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."11t_USUARIO" ADD CONSTRAINT "09t_USUARIO_PK" PRIMARY KEY CLUSTERED (IDUSUARIO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE dbo."12t_TERMINAL" 
    (
     IDTERMINAL INTEGER NOT NULL , 
     IDUNIDADEINST NVARCHAR (10) NOT NULL , 
     IDTIPOTERMINAL INTEGER NOT NULL , 
     IDUSUARIO NVARCHAR (100) NOT NULL , 
     IDUSUARIOLIBERACAO NVARCHAR (100) NOT NULL , 
     IDINSTITUICAO INTEGER NOT NULL , 
     IDPRODUTO INTEGER NOT NULL , 
     DATAPROCESSAMENTO DATETIME2 NOT NULL , 
     IDSITUACAOTERMINAL INTEGER NOT NULL , 
     DESCESTTRABALHO NVARCHAR (50) , 
     NUMULTAUTENTICACAO INTEGER NOT NULL , 
     NUMLOTECCO INTEGER NOT NULL , 
     MENORVALORNOTA NUMERIC (18,4) NOT NULL , 
     DATAHORALIBERACAO DATETIME2 NOT NULL , 
     NUMLOTECHEQUE INTEGER NOT NULL , 
     NUMULTSEQLANCCCO INTEGER NOT NULL , 
     NUMULTREMESSA INTEGER NOT NULL , 
     IDCLIENTECOR INTEGER , 
     NUMLOTEDOC INTEGER NOT NULL , 
     NUMULTSEQDOC INTEGER NOT NULL , 
     DESCVERSAOSO NVARCHAR (200) , 
     DESCMEMORIARAM NVARCHAR (50) , 
     DESCESPACODISCO NVARCHAR (50) , 
     DESCPACOTESERVICO NVARCHAR (50) , 
     NUMLOTEDEC INTEGER NOT NULL , 
     NUMULTSEQDEC INTEGER NOT NULL , 
     VALORLIMITESAQUE NUMERIC (18,4) NOT NULL , 
     VALORLIMITETERMINAL NUMERIC (18,4) NOT NULL , 
     NUMTESOUREIRO INTEGER , 
     NUMIPTESOUREIRO NVARCHAR (50) , 
     CODTIPOBALANCEAMENTO INTEGER , 
     NUMTIMEOUTDISPENSADOR INTEGER , 
     CODLADODEPOSITARIO INTEGER , 
     NUMPORTATESOUREIRO INTEGER , 
     NUMCHEKALTERACAO INTEGER , 
     CODCRIADOPOR INTEGER NOT NULL , 
     DATAHORACRIACAO DATETIME2 NOT NULL , 
     CODALTERADOPOR INTEGER , 
     DATAHORAALTERACAO DATETIME2 , 
     CODINATIVOPOR INTEGER , 
     DATAHORAINATIVO DATETIME2 
    )
GO

ALTER TABLE dbo."12t_TERMINAL" ADD CONSTRAINT "07t_TERMINAL_PK" PRIMARY KEY CLUSTERED (IDTERMINAL)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE dbo."00t_PARAMETRIZACAO" 
    ADD CONSTRAINT "00t_PARAMETRIZACAO_02t_USUARIOSISTEMA_FK" FOREIGN KEY 
    ( 
     CODALTERADOPOR
    ) 
    REFERENCES dbo."02t_USUARIOSISTEMA" 
    ( 
     IDUSUARIOSISTEMA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."07t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES" 
    ADD CONSTRAINT "00t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES_03t_TRANSPORTADORAVALORES_FK" FOREIGN KEY 
    ( 
     IDTRANSPORTADORAVALORES
    ) 
    REFERENCES dbo."06t_TRANSPORTADORAVALORES" 
    ( 
     IDTRANSPORTADORAVALORES 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."07t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES" 
    ADD CONSTRAINT "00t_UNIDADEINSTITUICAOTRANSPORTADORAVALORES_04t_UNIDADEINSTITUICAO_FK" FOREIGN KEY 
    ( 
     IDUNIDADEINST
    ) 
    REFERENCES dbo."05t_UNIDADEINSTITUICAO" 
    ( 
     IDUNIDADEINST 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."04t_USUARIOSISTEMAGRUPOACESSO" 
    ADD CONSTRAINT "00t_USUARIOSISTEMAGRUPOACESSO_00t_GRUPOACESSO_FK" FOREIGN KEY 
    ( 
     IDGRUPOACESSO
    ) 
    REFERENCES dbo."03t_GRUPOACESSO" 
    ( 
     IDGRUPOACESSO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."04t_USUARIOSISTEMAGRUPOACESSO" 
    ADD CONSTRAINT "00t_USUARIOSISTEMAGRUPOACESSO_02t_USUARIOSISTEMA_FK" FOREIGN KEY 
    ( 
     IDUSUARIOSISTEMA
    ) 
    REFERENCES dbo."02t_USUARIOSISTEMA" 
    ( 
     IDUSUARIOSISTEMA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."01t_CARGA" 
    ADD CONSTRAINT "01t_CARGA_02t_USUARIOSISTEMA_FK" FOREIGN KEY 
    ( 
     IDUSUARIOSISTEMA
    ) 
    REFERENCES dbo."02t_USUARIOSISTEMA" 
    ( 
     IDUSUARIOSISTEMA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."02t_USUARIOSISTEMA" 
    ADD CONSTRAINT "02t_USUARIOSISTEMA_08t_USUARIO_FK" FOREIGN KEY 
    ( 
     IDUSUARIO
    ) 
    REFERENCES dbo."11t_USUARIO" 
    ( 
     IDUSUARIO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."08t_TIPOTERMINAL" 
    ADD CONSTRAINT "04t_TIPOTERMINAL_06t_UNIDADEINSTITUICAO_FK" FOREIGN KEY 
    ( 
     IDUNIDADEINST
    ) 
    REFERENCES dbo."05t_UNIDADEINSTITUICAO" 
    ( 
     IDUNIDADEINST 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."10t_OPERACAO" 
    ADD CONSTRAINT "05t_OPERACAO_04t_TIPOTERMINAL_FK" FOREIGN KEY 
    ( 
     IDTIPOTERMINAL
    ) 
    REFERENCES dbo."08t_TIPOTERMINAL" 
    ( 
     IDTIPOTERMINAL 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."10t_OPERACAO" 
    ADD CONSTRAINT "05t_OPERACAO_06t_UNIDADEINSTITUICAO_FK" FOREIGN KEY 
    ( 
     IDUNIDADEINST
    ) 
    REFERENCES dbo."05t_UNIDADEINSTITUICAO" 
    ( 
     IDUNIDADEINST 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."10t_OPERACAO" 
    ADD CONSTRAINT "06t_OPERACAO_08t_TIPOOPERACAO_FK" FOREIGN KEY 
    ( 
     IDTIPOOPERACAO
    ) 
    REFERENCES dbo."09t_TIPOOPERACAO" 
    ( 
     IDTIPOOPERACAO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."12t_TERMINAL" 
    ADD CONSTRAINT "07t_TERMINAL_04t_UNIDADEINSTITUICAO_FK" FOREIGN KEY 
    ( 
     IDUNIDADEINST
    ) 
    REFERENCES dbo."05t_UNIDADEINSTITUICAO" 
    ( 
     IDUNIDADEINST 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."12t_TERMINAL" 
    ADD CONSTRAINT "07t_TERMINAL_05t_TIPOTERMINAL_FK" FOREIGN KEY 
    ( 
     IDTIPOTERMINAL
    ) 
    REFERENCES dbo."08t_TIPOTERMINAL" 
    ( 
     IDTIPOTERMINAL 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."12t_TERMINAL" 
    ADD CONSTRAINT "07t_TERMINAL_09t_USUARIO_FK" FOREIGN KEY 
    ( 
     IDUSUARIO
    ) 
    REFERENCES dbo."11t_USUARIO" 
    ( 
     IDUSUARIO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."12t_TERMINAL" 
    ADD CONSTRAINT "07t_TERMINAL_09t_USUARIO_FKv1" FOREIGN KEY 
    ( 
     IDUSUARIOLIBERACAO
    ) 
    REFERENCES dbo."11t_USUARIO" 
    ( 
     IDUSUARIO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE dbo."11t_USUARIO" 
    ADD CONSTRAINT "08t_USUARIO_04t_UNIDADEINSTITUICAO_FK" FOREIGN KEY 
    ( 
     IDUNIDADEINST
    ) 
    REFERENCES dbo."05t_UNIDADEINSTITUICAO" 
    ( 
     IDUNIDADEINST 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO